version: '3.9'

networks:
  kubelab-net:
    driver: overlay

volumes:
  mysql-data:

services:
  frontend:
    image: node:16-alpine
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "npm install && npm run start"
    ports:
      - "${FRONTEND_PORT}:3000"
    networks:
      - kubelab-net

  backend:
    image: node:16-alpine
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "${BACKEND_PORT}:5000"
    networks:
      - kubelab-net
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - kubelab-net

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: ${PHPMYADMIN_HOST}
      PMA_USER: ${PHPMYADMIN_USER}
      PMA_PASSWORD: ${PHPMYADMIN_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - kubelab-net
