version: '3.9'

networks:
  kubelab-net:
    driver: bridge

volumes:
  mysql-data:

services:
  # Frontend Service
  frontend:
    image: node:16-alpine
    container_name: kubelab-frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app   # Map din frontend-mappe
    command: sh -c "npm install && npm run start"
    ports:
      - "${FRONTEND_PORT}:3000"  # Frontend eksponeres på variabel port
    networks:
      - kubelab-net

  # Backend Service
  backend:
    image: node:16-alpine
    container_name: kubelab-backend
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app   # Map din backend-mappe
    command: sh -c "npm install && npm run dev"
    ports:
      - "${BACKEND_PORT}:5000"   # Backend eksponeres på variabel port
    networks:
      - kubelab-net
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}

  # Database Service
  db:
    image: mysql:8
    container_name: kubelab-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - kubelab-net

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: kubelab-phpmyadmin
    environment:
      PMA_HOST: ${PHPMYADMIN_HOST}
      PMA_USER: ${PHPMYADMIN_USER}
      PMA_PASSWORD: ${PHPMYADMIN_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - kubelab-net
