#
# Login on specific services
#
# | Database | Server | Username | Password  | Port  |
# | :------- | :----- | :------- | :-------- | :---- |
# | MSSQL    | mssql  | sa       | Ladida.12 | 1433  |
# | MySQL    | mysql  | root     | root      | 3306  |
# | Postgres | pgsql  | root     | root      | 5432  |
# | MongoDB  | mongo  | root     | root      | 27017 |
# | Redis    | redis  | -        | -         | 6379  |
#
# Choosing the right web interface for tools in this gist
#
# - Adminer - http://localhost:8081
#   - mssql
#   - mysql
#   - pgsql
# - Mongo Express - http://localhost:8082
#   - mongo
# - Redis Insights - http://localhost:8083
#   - redis
# - pgAdmin - http://localhost:8084
#   - pgsql
# - phpMyAdmin - http://localhost:8085
#   - mysql
#
# How to spin up
#   `docker compose -f database-compose.yml up -d`
#
# How to spin down
#   `docker compose -f database-compose.yml down`
#

version: '3.9'

volumes:
  mssql-data:
  mysql-data:
  pgsql-data:
  mongo-data:
  redis-data:

services:
  mssql:
    container_name: db-mssql
    #image: mcr.microsoft.com/azure-sql-edge:latest
    image: mcr.microsoft.com/mssql/server
    restart: unless-stopped
    cap_add: [ 'SYS_PTRACE' ]
    user: root
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: y
      MSSQL_SA_PASSWORD: Ladida.12

  mysql:
    container_name: db-mysql
    image: mysql:8
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  pgsql:
    container_name: db-pgsql
    image: postgres:14
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  mongo:
    container_name: db-mongo
    image: mongo:7
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  redis:
    container_name: db-redis
    image: redis:7.4-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  adminer:
    container_name: db-adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080

  mongo-express:
    container_name: db-mongo-express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root

  redis-insight:
    container_name: db-redis-insight
    image: redis/redisinsight:latest
    restart: unless-stopped
    ports:
      - 8083:5540

  pgadmin:
    container_name: db-pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 8084:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@local.dk
      PGADMIN_DEFAULT_PASSWORD: root

  phpmyadmin:
    container_name: db-phpmyadmin
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8085:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
